making sure ansible and deploy-aws.yml work properly

diff --git a/.github/workflows/deploy_aws.yml b/.github/workflows/deploy_aws.yml
--- a/.github/workflows/deploy_aws.yml
+++ b/.github/workflows/deploy_aws.yml
@@ -175,14 +175,14 @@ jobs:
           username: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN_USERNAME }}
           password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN1 }}
 
-      - name: Checking if docker image exist
-        if: ${{ inputs.ring == 'lab' }}
-        run: |
-          if (( $(jf rt s "https://deploydemo.jfrog.io/artifactory/*" --count) ==  0 )); then
-            echo "ERROR: Tag ${{ steps.trim-export.outputs.application_version_tag }} not found in JFrog"
-          exit 1
-          else
-            echo "Tag ${{ steps.trim-export.outputs.application_version_tag }} found in JFrog"
+#      - name: Checking if docker image exist
+#        if: ${{ inputs.ring == 'lab' }}
+#        run: |
+#          if (( $(jf rt s "https://deploydemo.jfrog.io/artifactory/docker/microservice1/${{ steps.trim-export.outputs.application_version_tag }}/*" --count) ==  0 )); then
+#            echo "ERROR: Tag ${{ steps.trim-export.outputs.application_version_tag }} not found in JFrog"
+#          exit 1
+#          else
+#            echo "Tag ${{ steps.trim-export.outputs.application_version_tag }} found in JFrog"
           fi
 
       - uses: actions/checkout@v3
